enum ShopTypes {
  FETCH_COLLECTIONS_REQUEST = "FETCH_COLLECTIONS_REQUEST",
  FETCH_COLLECTIONS_SUCCESS = "FETCH_COLLECTIONS_SUCCES",
  FETCH_COLLECTIONS_FAILURE = "FETCH_COLLECTION_FAILURE"
}

export default ShopTypes;
